name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Clean
      run: dotnet clean ./TweetAutomationProject.sln --configuration Debug && dotnet nuget locals all --clear     
  
    - name: Restore dependencies
      run: dotnet restore ./UserInterface/UserInterface.csproj
      
    - name: Restore dependencies
      run: dotnet restore ./UnitTesting/UnitTesting.csproj
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
